hostname r1
log stdout informational
service integrated-vtysh-config
ip forwarding
ipv6 forwarding
!
interface lo
 ip address 10.255.0.1/32
 ipv6 address fd00:255::1/128
 ip router isis 1
 ipv6 router isis 1
 isis passive
!
interface eth1
 ip address 10.0.1.2/30
!
interface eth2
 ip address 10.1.12.1/30
 ipv6 address fd00:1:12::1/64
 link-params
 exit-link-params
 ip router isis 1
 ipv6 router isis 1
 isis circuit-type level-2
 isis hello-interval 1
 isis hello-multiplier 3
 no isis hello padding
 isis network point-to-point
 isis metric 10
!
interface eth3
 ip address 10.1.13.1/30
 ipv6 address fd00:1:13::1/64
 link-params
 exit-link-params
 ip router isis 1
 ipv6 router isis 1
 isis circuit-type level-2
 isis hello-interval 1
 isis hello-multiplier 3
 no isis hello padding
 isis network point-to-point
 isis metric 10
!
interface eth4
 ip address 10.1.17.1/30
 ipv6 address fd00:1:17::1/64
 link-params
 exit-link-params
 ip router isis 1
 ipv6 router isis 1
 isis circuit-type level-2
 isis hello-interval 1
 isis hello-multiplier 3
 no isis hello padding
 isis network point-to-point
 isis metric 25
!
router isis 1
 net 49.0001.0000.0000.0001.00
 is-type level-2-only
 hostname dynamic
 log-adjacency-changes
 metric-style wide
 redistribute ipv4 connected level-2
 redistribute ipv6 connected level-2
 lsp-mtu 1492
 lsp-gen-interval 1
 lsp-refresh-interval 10
 max-lsp-lifetime 350
 mpls-te on
 mpls-te router-address 10.255.0.1
 mpls-te router-address ipv6 fd00:255::1
 mpls-te export
!
router bgp 65000
 bgp router-id 10.255.0.1
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 10.0.1.1 remote-as 65000
 neighbor 10.0.1.1 description bgPLS collector
 neighbor 10.0.1.1 timers 3 9
 !
 address-family link-state
  neighbor 10.0.1.1 activate
 exit-address-family
!
