hostname r4
log stdout informational
service integrated-vtysh-config
ip forwarding
ipv6 forwarding
!
interface lo
 ip address 10.255.0.4/32
 ipv6 address fd00:255::4/128
 ip router isis 1
 ipv6 router isis 1
 isis passive
!
interface eth1
 ip address 10.1.24.2/30
 ipv6 address fd00:1:24::2/64
 link-params
 exit-link-params
 ip router isis 1
 ipv6 router isis 1
 isis circuit-type level-2
 isis hello-interval 1
 isis hello-multiplier 3
 no isis hello padding
 isis network point-to-point
 isis metric 10
!
interface eth2
 ip address 10.1.34.2/30
 ipv6 address fd00:1:34::2/64
 link-params
 exit-link-params
 ip router isis 1
 ipv6 router isis 1
 isis circuit-type level-2
 isis hello-interval 1
 isis hello-multiplier 3
 no isis hello padding
 isis network point-to-point
 isis metric 15
!
interface eth3
 ip address 10.1.45.1/30
 ipv6 address fd00:1:45::1/64
 link-params
 exit-link-params
 ip router isis 1
 ipv6 router isis 1
 isis circuit-type level-2
 isis hello-interval 1
 isis hello-multiplier 3
 no isis hello padding
 isis network point-to-point
 isis metric 20
!
interface eth4
 ip address 10.1.46.1/30
 ipv6 address fd00:1:46::1/64
 link-params
 exit-link-params
 ip router isis 1
 ipv6 router isis 1
 isis circuit-type level-2
 isis hello-interval 1
 isis hello-multiplier 3
 no isis hello padding
 isis network point-to-point
 isis metric 20
!
router isis 1
 net 49.0001.0000.0000.0004.00
 is-type level-2-only
 hostname dynamic
 log-adjacency-changes
 metric-style wide
 redistribute ipv4 connected level-2
 redistribute ipv6 connected level-2
 lsp-mtu 1492
 lsp-gen-interval 1
 lsp-refresh-interval 10
 max-lsp-lifetime 350
 mpls-te on
 mpls-te router-address 10.255.0.4
 mpls-te router-address ipv6 fd00:255::4
!
