hostname r7
log stdout informational
service integrated-vtysh-config
ip forwarding
ipv6 forwarding
!
interface lo
 ip address 10.255.0.7/32
 ipv6 address fd00:255::7/128
 ip router isis 1
 ipv6 router isis 1
 isis passive
!
interface eth1
 ip address 10.1.17.2/30
 ipv6 address fd00:1:17::2/64
 link-params
 exit-link-params
 ip router isis 1
 ipv6 router isis 1
 isis circuit-type level-2
 isis hello-interval 1
 isis hello-multiplier 3
 isis network point-to-point
 isis metric 25
!
interface eth2
 ip address 10.1.57.2/30
 ipv6 address fd00:1:57::2/64
 link-params
 exit-link-params
 ip router isis 1
 ipv6 router isis 1
 isis circuit-type level-2
 isis hello-interval 1
 isis hello-multiplier 3
 isis network point-to-point
 isis metric 25
!
interface eth3
 ip address 10.1.78.1/30
 ipv6 address fd00:1:78::1/64
 link-params
 exit-link-params
 ip router isis 1
 ipv6 router isis 1
 isis circuit-type level-2
 isis hello-interval 1
 isis hello-multiplier 3
 isis network point-to-point
 isis metric 30
!
interface eth4
 ip address 10.1.79.1/30
 ipv6 address fd00:1:79::1/64
 link-params
 exit-link-params
 ip router isis 1
 ipv6 router isis 1
 isis circuit-type level-2
 isis hello-interval 1
 isis hello-multiplier 3
 isis network point-to-point
 isis metric 25
!
router isis 1
 net 49.0001.0000.0000.0007.00
 is-type level-2-only
 hostname dynamic
 log-adjacency-changes
 topology ipv6-unicast
 redistribute ipv4 connected level-2
 redistribute ipv6 connected level-2
 lsp-gen-interval 1
 lsp-refresh-interval 10
 max-lsp-lifetime 350
 mpls-te on
 mpls-te router-address 10.255.0.7
 mpls-te router-address ipv6 fd00:255::7
!
