hostname r7
frr defaults datacenter
log stdout informational
service integrated-vtysh-config
ip forwarding
ipv6 forwarding
!
interface lo
 ip address 10.255.0.7/32
 ipv6 address fd00:255::7/128
 ip router isis 1
 ipv6 router isis 1
 isis passive
exit
!
interface eth1
 ip address 10.1.17.2/30
 ipv6 address fd00:1:17::2/64
 ip router isis 1
 ipv6 router isis 1
 isis network point-to-point
 isis circuit-type level-2
 isis metric 25
 isis hello-interval 1
 isis hello-multiplier 4
 link-params
  enable
  metric 25
  max-bw 125000000
  max-rsv-bw 125000000
  unrsv-bw 0 125000000
  delay 800
  admin-grp 8
 exit-link-params
exit
!
interface eth2
 ip address 10.1.57.2/30
 ipv6 address fd00:1:57::2/64
 ip router isis 1
 ipv6 router isis 1
 isis network point-to-point
 isis circuit-type level-2
 isis metric 25
 isis hello-interval 1
 isis hello-multiplier 4
 link-params
  enable
  metric 25
  max-bw 125000000
  max-rsv-bw 125000000
  unrsv-bw 0 125000000
  delay 800
  admin-grp 8
 exit-link-params
exit
!
interface eth3
 ip address 10.1.78.1/30
 ipv6 address fd00:1:78::1/64
 ip router isis 1
 ipv6 router isis 1
 isis network point-to-point
 isis circuit-type level-2
 isis metric 30
 isis hello-interval 1
 isis hello-multiplier 4
 link-params
  enable
  metric 30
  max-bw 125000000
  max-rsv-bw 125000000
  unrsv-bw 0 125000000
  delay 800
  admin-grp 8
 exit-link-params
exit
!
router isis 1
 net 49.0001.0102.5500.0007.00
 is-type level-2-only
 metric-style wide
 hostname dynamic
 log-adjacency-changes
 topology ipv6-unicast
 lsp-gen-interval 5
 spf-interval 5
 mpls-te on
 mpls-te router-address 10.255.0.7
 mpls-te export
exit
!
router bgp 65000
 bgp router-id 10.255.0.7
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 bgp log-neighbor-changes
 neighbor 10.255.0.1 remote-as 65000
 neighbor 10.255.0.1 update-source lo
 neighbor 10.255.0.1 description BGP-LS route reflector
 !
 address-family ipv4 unicast
  no neighbor 10.255.0.1 activate
 exit-address-family
 !
 address-family link-state
  neighbor 10.255.0.1 activate
 exit-address-family
exit
!
